### PR TITLE
done with tagComponent 

### PR DESCRIPTION
**Pull request by amrmohamedmero**

### CODE REVIEW

**Comment by youssefMoJo** [comment]
Changed the component name from CustomComponent to TagComponent

**Review by FadyAPhilips — CHANGES_REQUESTED** [review]
Add an x that would remove the tag.
The width should just be fit content. no need for prop
Th fontFamily will be a general font for the app no need for prop.
hard codeborder radius to 50%

**Review by FadyAPhilips — CHANGES_REQUESTED** [review]
CloseSize should just be dependant on the font size. eg if font is 12, close size could be 12 * 1.2 and hard code that number for consistancy.
Also Be careful and use camel case for CloseSize (even though you will remove it)
give height a default value.
Make it so that the close button takes in a callback function onClick. The logic of the closing should be done by the parent from removing the tag from the array.

**Comment by amrmohamedmero** [comment]
Done with these changes

**Review by FadyAPhilips — APPROVED** [review]
change the name of the onClick prop because onClick is already a native prop in html. I'm not sure but this could cause confussion.
Everything else looks good so I will approve

**Pull request merged**
